#### Download datasets for the analysis of the yeast cell cycle transcriptome ####
##
## This script was generated by iterative prompting with ChatGPT 4.0
## as a demo for the workshop "Using generative AI to implement scripts for bioanalysis"
## organised in Paris on June 13, 2025, and adapted for the second edition on June 12, 2026. 
##

# ---- Parameters ----
REMOTE_BASE <- "https://ifb-elixirfr.github.io/AI-bioscripting-workshop"
REMOTE_DATA_DIR <- file.path(REMOTE_BASE, "data/yeast-transcriptome-cell-cycle")
WORK_DIR <- getwd() ## Adapt it as you like
ANALYSIS_DIR <- file.path(WORK_DIR, "analysis_yeast-transcriptome-cell-cycle")

## Data table: normalised counts
NORM_COUNTS_1705 <- "oscillating-genes_1705_normalized-profiles.tsv"
HEATMAP_FIGURE <- "heatmap_yeast_cell-cycle.png"
RAW_COUNTS_1705 <- "oscillating-genes_1705_normalized-profiles.tsv"

message("\tREMOTE_DATA_DIR\t", REMOTE_DATA_DIR)
message("\tANALYSIS_DIR\t", ANALYSIS_DIR)
dir.create(ANALYSIS_DIR, showWarnings = FALSE, recursive = TRUE)

# ---- Functions ----

#' Download and check yeast cell cycle dataset
#'
#' This function creates a target directory in the user's home folder,
#' downloads a tab-separated file from a public URL, and checks its presence and size.
#'
#' @param url The URL of the dataset to download.
#' @param target_dir The directory where the file should be saved.
#' @param filename The name to save the downloaded file as.
#' @return The path of the downloaded file if successful, otherwise throws an error.
#' @export
download_and_check_dataset <- function(url, target_dir, filename) {
  # Create the target directory if it doesn't exist
  if (!dir.exists(target_dir)) {
    dir_create(target_dir)
  }
  
  # Define the full path for the output file
  file_path <- file.path(target_dir, filename)
  
  # Download the file (overwrite = TRUE ensures re-download if needed)
  if (file.exists(file_path)) {
    message("\tSkipping download, file already present\t", filename)
  } else {
    message("\tDownloading file\t", filename)
    download.file(url, destfile = file_path, mode = "wb")
  }
  
  # Check if the file exists and is not empty
  if (!file.exists(file_path)) {
    stop("File was not downloaded.")
  }
  if (file.info(file_path)$size == 0) {
    stop("Downloaded file is empty.")
  }
  
  return(file_path)
}

# ---- Download ----

download_and_check_dataset(url = REMOTE_DATA_DIR, target_dir = ANALYSIS_DIR, filename = NORM_COUNTS_1705)
download_and_check_dataset(url = REMOTE_DATA_DIR, target_dir = ANALYSIS_DIR, filename = HEATMAP_FIGURE)

